### ISSUE TITLE
Docker container unreachable from a different host on the same calico network

### ISSUE THREAD

**Issue by bmikhael** [projectcalico/calico-cni#138] opened 2016-08-11 07:25 UTC
I've created a three nodes calico-docker-kubernetes cluster.
I can't reach a Docker container created by Kubernetes from a different node than where it is living.
OS: OEL7.2
kernel: 3.10.0-327.22.2.el7.x86_64

```
# calicoctl  endpoint show --detailed
+-------------------------+-----------------+------------------------------------------------------------------+----------------------------------+-----------------+-------------------+--------------------+--------+
| Hostname | Orchestrator ID |                           Workload ID                            |           Endpoint ID            |    Addresses    |        MAC        |      Profiles      | State  |
+-------------------------+-----------------+------------------------------------------------------------------+----------------------------------+-----------------+-------------------+--------------------+--------+
| node02   |       cni       | 0a63856679e4bd115ea184ed725dba14d61cceb555a175665870f57e65684b58 | e1d86f765f9011e6aff19cb65496f440 | 192.168.0.66/32 | ca:73:49:7d:34:f6 | calico-k8s-network | active |
| node03   |       cni       | 14ea56b3317c3443635499f01df8a66f5937169c64f280130a4cb4f082b48534 | dc53f8ce5f8e11e6898bf0921c0d2ee0 |  192.168.0.0/32 | 72:81:0d:9f:44:b1 | calico-k8s-network | active |
| node03   |       cni       | 25bcae68eb0b54108cad4a6fc8c0463488db187110428e4e4125c713e454d733 | ca1087845f9011e698a7f0921c0d2ee0 |  192.168.0.2/32 | 4e:ea:de:ba:6e:de | calico-k8s-network | active |
+-------------------------+-----------------+------------------------------------------------------------------+----------------------------------+-----------------+-------------------+--------------------+--------+
```

```
# calicoctl status
calico-node container is running. Status: Up About an hour
Running felix version 1.4.0rc2

IPv4 BGP status
IP: <NODE01-IP>    AS Number: 65401 (inherited)
+---------------+-------------------+-------+----------+-------------+
|  Peer address |     Peer type     | State |  Since   |     Info    |
+---------------+-------------------+-------+----------+-------------+
| <NODE02-IP>   | node-to-node mesh |   up  | 07:10:26 | Established |
| <NODE03-IP>   | node-to-node mesh |   up  | 06:10:48 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 address configured.
```

That's the routing table on node-01:
```
# ip route
default via <ToR-IP> dev eth0 
<ToR-NET>/25 dev eth0  proto kernel  scope link  src <NODE01-IP> 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.0.0/26 via <NODE03-IP> dev eth0  proto bird 
```

That's the routing table on node-02:
```
# ip route
default via <ToR-IP> dev eth0 
<ToR-NET>/25 dev eth0  proto kernel  scope link  src <NODE02-IP> 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.0.0/26 via <NODE03-IP> dev eth0  proto bird 
blackhole 192.168.0.64/26  proto bird 
192.168.0.66 dev calie1d86f765f9  scope link 
```

That's the routing table on node-03:
```
# ip route
default via <ToR-IP> dev eth0 
<ToR-NET>/25 dev eth0  proto kernel  scope link  src <NODE03-IP>  
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.0.0 dev calidc53f8ce5f8  scope link 
blackhole 192.168.0.0/26  proto bird 
192.168.0.2 dev calica1087845f9  scope link 
```

**Comment by caseydavenport** [comment] 2016-08-11 17:47
@bmikhael Could you share what version of the CNI plugin you're using?  The workload IDs in the output you provided indicate that it is a relatively old version.  I'd suggest updating to the latest release.

It would also be helpful to understand how your nodes are configured.  Are you using a L3 TOR, or are your nodes all on the same L2 network?

**Comment by bmikhael** [comment] 2016-08-11 18:00
I'm using CNI version 1.0.0
I got it from this link https://github.com/projectcalico/calico-cni/releases/download/v1.0.0/calico
and I've got Calicoctl from this link https://github.com/projectcalico/calico-containers/releases/download/v0.20.0/calicoctl
That's my Calico CNI configuration:
```
# cat /etc/cni/net.d/10-calico.conf
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_authority": "127.0.0.1:2379",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam"
    }
}
```
I'm using an L3 ToR (Cisco nexus 3064).

**Comment by caseydavenport** [comment] 2016-08-11 19:52
How are you making sure that the L3 ToR is able to route to your k8s pods?

My guess for why cross-host isn't working is because the ToR doesn't have routes to the pod IP range, give your Calico BGP peerings are between each other and not with the ToR.

You probably want to configure BGP peerings between Calico and your ToR so that it is aware of pods.

**Comment by bmikhael** [comment] 2016-08-11 20:41
I've BGP peering with the ToR.
```
# calicoctl pool show
+----------------+---------+
|   IPv4 CIDR    | Options |
+----------------+---------+
| 10.10.48.64/26 |         |
+----------------+---------+
+--------------------------+---------+
|        IPv6 CIDR         | Options |
+--------------------------+---------+
| fd80:24e2:f998:72d6::/64 |         |
+--------------------------+---------+
# calicoctl bgp peer add <ToR-IP> as 65152
# calicoctl bgp peer show
+----------------------+--------+
| Global IPv4 BGP Peer | AS Num |
+----------------------+--------+
| <ToR-IP>             | 65152  |
+----------------------+--------+
No global IPv6 BGP Peers defined.
```

plus, I'm trying to talk to a container on a node from another node on the same Calico network, which means that even if there is no ToR, I shouldn't have a problem getting the nodes in the same Calico network talk to each other.

**Comment by caseydavenport** [comment] 2016-08-11 20:53
Even if the two nodes are in the same Calico deployment, if the data path includes the ToR then it needs to know how to route to the pod IP address.

Can you confirm that the BGP session between Calico and the ToR is Established, or that the data path doesn't include the ToR for the traffic you're testing?

**Comment by bmikhael** [comment] 2016-08-11 22:25
The BGP session is configured between the Calico nodes and the ToR, the ToR is receiving advertisements from Calico.
But I see the following error in k8s when I create a new pod.
`Error syncing pod, skipping: failed to "SetupNetwork" for "kubernetes-dashboard-v1.1.0-68082_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kubernetes-dashboard-v1.1.0-68082_kube-system(1c18acd7-6012-11e6-8b7b-9cb6549b27c0)\" using network plugins \"cni\": Unhandled Exception killed plugin; Skipping pod"`

**Comment by bmikhael** [comment] 2016-08-11 22:30
Also I've tried to bypass k8s. So I created a network in Docker as follows:
```
# docker network create --driver calico --ipam-driver calico calnet
a98867883e05adf9eb90f3da62f98130b3d7e411a3ab6070252a2ac65325c1d6
```

```
# docker network ls
NETWORK ID          NAME                DRIVER
a98867883e05        calnet              calico              
54945a278607        bridge              bridge              
37c1a50bd13f        none                null                
19d9dcbb8803        host                host
```

```
# docker run --net calnet --name workload-A -tid busybox
e5ef9e3754aa0079701534832c3ac46c061d0001c2c0e00f14ff13ffa33e3958
Error response from daemon: Cannot start container e5ef9e3754aa0079701534832c3ac46c061d0001c2c0e00f14ff13ffa33e3958: Plugin Error: IpamDriver.RequestAddress, {
  "Err": ""
}

```

**Comment by caseydavenport** [comment] 2016-08-22 19:56
@bmikhael This error looks like a problem, for sure:

```
Error syncing pod, skipping: failed to "SetupNetwork" for "kubernetes-dashboard-v1.1.0-68082_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kubernetes-dashboard-v1.1.0-68082_kube-system(1c18acd7-6012-11e6-8b7b-9cb6549b27c0)\" using network plugins \"cni\": Unhandled Exception killed plugin; Skipping pod"
```

Could you check the contents of `/var/log/calico/cni/cni.log` to see if there is more context for that failure?

**Comment by caseydavenport** [comment] 2016-09-03 05:34
@bmikhael Did you get a chance to look at those logs?

**Comment by caseydavenport** [comment] 2016-09-19 06:01
@bmikhael - Closing this for now due to inaction, please let me know if you manage to reproduce on the latest CNI release (v1.4.1) and I'll re-open!

**Comment by bmikhael** [comment] 2016-09-19 23:07
@caseydavenport I've changed the kernel used and upgraded Calico CNI version. My setup is as follows:
OS: OEL 7.2
Kernel: 4.4.20-1.el7.elrepo.x86_64
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:06:06Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```
```
# etcdctl --version
etcdctl version 2.3.7
```
```
# docker version
Boolean docker_transition_unconfined is not defined
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64
```
```
# calico -v
v1.4.1
```
```
# calicoctl version
0.21.0
```
Now, the error looks close to the old one but with difference in no being able to find the plugin.
`Error syncing pod, skipping: failed to "SetupNetwork" for "kubernetes-dashboard-v1.1.0-se5qs_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kubernetes-dashboard-v1.1.0-se5qs_kube-system(2c78e8f1-7eb8-11e6-b0af-080027840464)\" using network plugins \"cni\": could not find \".\" plugin; Skipping pod"`

**Comment by bmikhael** [comment] 2016-09-20 00:15
PS: there is no `/var/log/calico/cni/cni.log`
That's the contents of calico logs directory:
```
# ls /var/log/calico/
bird  bird6  confd  felix  felix.log
```

**Comment by caseydavenport** [comment] 2016-09-20 00:23
@bmikhael Yeah, the log won't exist for two reasons:

1) v1.4.1 doesn't log to file anymore - you can find the log output in the kubelet log (journalctl -u kubelet most likely)
2) It doesn't look like the CNI plugin is being found by the kubelet, and thus isn't being called.

The version information you posed all looks just fine to me.

` could not find \".\" plugin`, while a terrible error message, is usually a result of either the CNI config being subtly wrong, or the plugin not being located where Kubernetes expects it.  I'd double check those are correct.

**Comment by bmikhael** [comment] 2016-09-20 00:41
That's how I configured calico CNI for K8s:
```
# cat /etc/cni/net.d/10-calico.conf
{
	"name": "calico-k8s-network",
	"type": "calico",
	"etcd_authority": "127.0.0.1:2379",
	"log_level": "info",
	"ipam": {
		"type": "calico-ipam"
	},
	"policy": {
		"type": "k8s"
	}
}
```

and That's the status for kubelet:
```
# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-09-19 15:55:06 PDT; 1h 2min ago
     Docs: https://github.com/kubernetes/kubernetes
 Main PID: 3005 (kubelet)
   Memory: 97.7M
   CGroup: /system.slice/kubelet.service
           ├─3005 /usr/bin/kubelet --logtostderr=true --v=0 --allow-privileged=True --api-servers=http://{MASTER_IP}:8080 --config=/etc/kubernetes/manifests --network-plugin=cni --network-plugin-dir=/etc/cni/net.d --cluster-dns=10.0.0.10 --cluster-domain=cluster.local --register-node=true --register-schedulable=false
           └─4719 journalctl -k -f
```

I did the same for calico CNI 1.0.0 with k8s 1.2.4 and it worked fine.

**Comment by caseydavenport** [comment] 2016-09-30 19:47
Your kubelet config looks correct, as does the CNI network config.  It still feels to me like the kubelet is failing to find the binaries for some reason.  So long as you have the `calico` and `calico-ipam` binaries installed in `/opt/cni/bin`, I'm not sure what else might be going wrong.

**Comment by bmikhael** [comment] 2016-10-04 22:27
@caseydavenport Here is what I've changed to get it working:
I've placed calico and calico-ipam binaries in this directory /opt/cni/bin/
```
# wget -P /usr/bin https://github.com/projectcalico/calico-containers/releases/download/v0.22.0/calicoctl --no-check-certificate
# wget -N -P /opt/cni/bin https://github.com/projectcalico/calico-cni/releases/download/v1.4.0/calico
# wget -N -P /opt/cni/bin https://github.com/projectcalico/calico-cni/releases/download/v1.4.2/calico-ipam
# chmod +x /usr/bin/calicoctl
# chmod +x /opt/cni/bin/calico
# chmod +x /opt/cni/bin/calico-ipam
```
Calico CNI configuration looks like this:
```
# cat /etc/cni/net.d/10-calico.conf
{
	"name": "calico-k8s-network",
	"type": "calico",
	"etcd_authority": "127.0.0.1:2379",
	"log_level": "info",
	"ipam": {
		"type": "calico-ipam"
	},
	"policy": {
		"type": "k8s",
		"k8s_api_root": "http://${MASTER_IP}:8080"
	}
}
```

The big difference is in the unit file (as I'm using systemd):
```
# cat /usr/lib/systemd/system/calico-node.service
[Unit]
Description=calicoctl node
After=docker.service
Requires=docker.service

[Service]
User=root
Environment=ETCD_AUTHORITY=127.0.0.1:2379
PermissionsStartOnly=true
ExecStart=/usr/bin/calicoctl node --ip=${MASTER_IP} --libnetwork
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```
Instead of the unit file example stated in this documentation https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/KubernetesIntegration.md:
```
[Unit]
Description=calicoctl node
After=docker.service
Requires=docker.service

[Service]
User=root
Environment=ETCD_ENDPOINTS=http://<ETCD_IP>:<ETCD_PORT>
PermissionsStartOnly=true
ExecStartPre=/usr/bin/wget -N -P /opt/bin http://www.projectcalico.org/builds/calicoctl
ExecStartPre=/usr/bin/chmod +x /opt/bin/calicoctl
ExecStart=/opt/bin/calicoctl node --detach=false
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```
Without using libnetwork, kubelet and Docker were complaining from being unable to reach the CNI plugin. and to use libnetwork, I had to remove --detach=false

**Comment by caseydavenport** [comment] 2016-10-12 05:20
@bmikhael Hmm, I'm not sure I understand the fix and how the libnetwork plugin is related.  Docker shouldn't be looking for the CNI binaries, and kubelet doesn't do anything with libnetwork :) 

Glad it is working for you now though!

**Closed by caseydavenport** 2016-10-12 05:20 UTC
Labels: kind/support
