### ISSUE TITLE
calico-ipam binaries doesn't support self-reporting its version

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-cni#199] opened 2016-11-06 02:37 UTC
It's easy to add - just copy a little code from the main() function in the calico.go file to here https://github.com/projectcalico/calico-cni/blob/master/ipam/calico-ipam.go#L32

**Comment by caseydavenport** [comment] 2016-11-06 02:53
Duplicate of #195

**Closed by caseydavenport** 2016-11-06 02:53 UTC
